repos:
    # Python linter and code formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      # Run the linter.
      - id: ruff-check

      # Run the formatter.
      - id: ruff-format
        name: "ruff format"
        description: "This hook runs 'ruff format' for python code formatting."

    # Poetry hooks.
  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.3'
      hooks:
      - id: poetry-check
        name: "poetry check"
        description: "This hook runs 'poetry check --lock' for verifying that all python packages and dependencies are up-to-date."
        args: [ --lock ]