[tool.poetry]
name = "eu4 modding tools"
version = "0.1.0"
description = "A collection of scripts used for different modding purposes, including properly scaling UI, generating landscapes, checking grammar, and more."
authors = ["bjornbryggman"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Wand = "^0.6.13"
replicate = "^0.25.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
